Feature/add webhook
scenario-test-framework/stfw pull request #6
Opened 2018-01-11 09:21 UTC by tkhr-sait

**What kind of change does this PR introduce?**
- [x] feature
- [ ] bug fix
- [ ] docs update
- [ ] other

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our [guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [ ] Fix/Feature: Docs have been added/updated
- [x] Fix/Feature: Tests have been added; existing tests pass

**Does this PR introduce a breaking change?**
- [ ] yes
- [x] no

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Other information**:
#1

2018-01-11 13:24 UTC, suwa-sh commented
差分が把握しづらかったので、一回rebase & squashしましたf(^_^;
見てみますねー

2018-01-11 15:43 UTC, suwa-sh requested changes
だいぶそれらしい感じのpayloadになりましたね(^o^)/

細かい話が多いですが、気づいたところ（pluginの考慮以外）をまとめてコメント入れてみましたー

2018-01-11 15:43 UTC, suwa-sh commented on src/bin/lib/common_utils
> +function webhook.createhook() {
webhook.async_execute とかにしますか？
※参考: https://github.com/gitlabhq/gitlabhq/blob/master/app/models/hooks/web_hook.rb

2018-01-11 15:43 UTC, suwa-sh commented on src/bin/lib/common_utils
> +    _status="started"
今後の拡張で後続影響があるかもしれないので、localスコープにしておきたいです。

2018-01-11 15:43 UTC, suwa-sh commented on src/bin/lib/common_utils
> +    if [[ "$stfw_webhooks_on_start" = "false" ]]; then
boolean文字列の判定は ```!= "true"``` に統一したいです。

2018-01-11 15:43 UTC, suwa-sh commented on src/bin/lib/common_utils
> +    if [[ "$status" = "error" ]]; then
exportした環境変数で ```status``` って名前はさすがにゆるいので ```stfw_run_status``` とかにしておきたいです。

2018-01-11 15:43 UTC, suwa-sh commented on src/bin/lib/common_utils
> +
けっこう処理時間がかかってしまっているっぽいので
ここまでの早期リターン判定が終わったら、後続処理をまとめてバックグラウンド実行したいです。

2018-01-11 15:43 UTC, suwa-sh commented on src/bin/lib/common_utils
> +  local _configs=${STFW_PROJ_DIR_CONFIG}/webhook-payload.yml
```${DIR_CONFIG}/webhook/payload.yml``` など、stfwのインストールディレクトリ側で管理したいです。

2018-01-11 15:43 UTC, suwa-sh commented on src/bin/lib/common_utils
> +      _configs="$_configs ${STFW_PROJ_DIR_CONFIG}/webhook-run.yml"
他の変数参照も一律ですが、```$0``` ```$@``` ```$#``` などの特殊変数以外は、極力 ```${_configs}``` に倒したいです。
意図しない参照になってしまうバグが入りやすいのでf(^_^;

2018-01-11 15:43 UTC, suwa-sh commented on src/bin/lib/common_utils
> +  export STFW_SERVER_VERSION=$(digdag version 2> /dev/null | grep Server | cut -d' ' -f3)
digdagコマンドはPATH通してないです。。。下記な感じですかね？
1. stfw_digdag_utilsにバージョン取得のfunctionを追加
2. このfunctionはstfw_utilsに移動
3. stfw_utilsで、stfw_digdag_utilsをsourceして利用

2018-01-11 15:43 UTC, suwa-sh commented on src/bin/lib/common_utils
> +  env | grep stfw_webhooks_urls_ | cut -d= -f2 |
env コマンドは、危ないので使いたくないです。。。printenvで。

optionに連結して値を渡すのって、できるコマンドとできないのがあるので。。。
```cut -d '=' -f 2``` にしたいです。

2018-01-11 15:43 UTC, suwa-sh commented on src/bin/lib/common_utils
> +    curl -sS -X POST --data-binary "@/tmp/stfw_webhook.json.$$" -H "Content-type: application/json" $_webhooks_url &
curlのオプション、覚えきれないのでlong optionに統一したいですf(^_^;
※参考: bin/install

成功失敗がわかるように、ログは出しておきたいです。下記くらいで行けるかと。
* response codeを標準出力、response bodyを一時ファイル出力
* response codeの200系で正常終了を判断
* エラー時は response bodyをログ表示

2018-01-11 15:43 UTC, suwa-sh commented on src/bin/stfw
> +  echo "$*" > ${STFW_PROJ_DIR_DATA}/param
まだrun_id発行してないから、.stfw/ 直下にした感じですかね。
stfw runを複数並走させたら動かなそうですねf(^_^;
```export stfw_run_raw_parms="$*"``` とかで環境変数化してしまいますか？

2018-01-11 15:43 UTC, suwa-sh commented on src/template/stfw.yml
> +      - http://127.0.0.1:8000/1lazctj1
https://webhook.site とかにして、動かせるようにしておきますか？
これなら integration_test.sh & travis でも動かせるかと。

2018-01-12 00:09 UTC, suwa-sh commented on src/bin/lib/common_utils
> +
リターン判定も含めて、処理全体をバックグラウンドで大丈夫そうですねf(^_^;

今のfuncの枠は残して、privateなfunctに処理を移動。
枠だけになった今のfuncは、privateなfuncをバックグラウンドで呼び出すだけ。
くらいで行けるかとー

2018-01-12 09:23 UTC, tkhr-sait commented on src/bin/lib/common_utils
> +    curl -sS -X POST --data-binary "@/tmp/stfw_webhook.json.$$" -H "Content-type: application/json" $_webhooks_url &
指摘内容のイメージと違うかもですが、こんな感じでもOKですかね？
# post webhooks
  printenv | grep stfw_webhooks_urls_ | cut -d "=" -f 2 |
  while read -r _webhooks_url
  do
    curl                                         \
      --silent                                   \
      --show-error                               \
      --request POST                             \
      --data-binary "@/tmp/stfw_webhook.json.$$" \
      --header "Content-type: application/json"  \
      "${_webhooks_url}"                         | log.debug
    _retcode=${PIPESTATUS[0]}

    if [[ ${_retcode} -eq ${EXITCODE_SUCCESS} ]]; then
      log.info "webhook post to ${_webhooks_url}"
    else
      log.error "webhook post failed. target:${_webhooks_url}, retcode:${_retcode}"
    fi
  done
  rm /tmp/stfw_webhook.json.$$

成功時ログ(digdagのログ画面)
2018-01-12 18:16:37  INFO ---- webhook post to http://127.0.0.1:8000/1lazctj1

失敗時ログ(digdagのログ画面)
curl: (7) Failed to connect to 127.0.0.1 port 9999: 接続を拒否されました
2018-01-12 18:16:37 ERROR ---- webhook post failed. target:http://127.0.0.1:9999/erroraddress, retcode:7

2018-01-12 09:34 UTC, suwa-sh commented on src/bin/lib/common_utils
> +    curl -sS -X POST --data-binary "@/tmp/stfw_webhook.json.$$" -H "Content-type: application/json" $_webhooks_url &
--show-error なんてあるんですね！
良い感じだと思いますー(^o^)/

2018-01-12 14:14 UTC, tkhr-sait commented on src/bin/stfw
> +  echo "$*" > ${STFW_PROJ_DIR_DATA}/param
開始～終了時間のように、こんな感じでやろうかと。
　1.stfwで環境変数としてexport
　export stfw_run_raw_parms="$*" 
　2.これだけだと他cmd実行時引き継がれないので、
   webhook内でファイル（run_id付き）に書き出し＆読み出し

2018-01-12 14:17 UTC, tkhr-sait commented on src/bin/lib/common_utils
> +  export STFW_SERVER_VERSION=$(digdag version 2> /dev/null | grep Server | cut -d' ' -f3)
もともと
stfw_digdag_utils内で stfw_utils を sourceしているようなので、
1.3.をやってしまうと構成的にちょっと混乱しそうです..
2. でバージョン取得だと実装箇所的にちょっとおかしいですかね？

2018-01-12 22:30 UTC, tkhr-sait commented on src/bin/lib/common_utils
> +function webhook.createhook() {
指摘通り対応しましたー

2018-01-12 22:30 UTC, tkhr-sait commented on src/bin/lib/common_utils
> +    _status="started"
指摘通り対応しましたー

2018-01-12 22:30 UTC, tkhr-sait commented on src/bin/lib/common_utils
> +    if [[ "$stfw_webhooks_on_start" = "false" ]]; then
指摘通り対応しましたー

2018-01-12 22:30 UTC, tkhr-sait commented on src/bin/lib/common_utils
> +    if [[ "$status" = "error" ]]; then
指摘通り対応しましたー

2018-01-12 22:32 UTC, tkhr-sait commented on src/bin/lib/common_utils
> +
開始時刻を持っているファイルの削除タイミングなどもあるため、
curlでのpost部分をまとめてバックグラウンドにしました

2018-01-12 22:32 UTC, tkhr-sait commented on src/bin/lib/common_utils
> +  local _configs=${STFW_PROJ_DIR_CONFIG}/webhook-payload.yml
指摘通り対応しましたー

2018-01-12 22:33 UTC, tkhr-sait commented on src/bin/lib/common_utils
> +      _configs="$_configs ${STFW_PROJ_DIR_CONFIG}/webhook-run.yml"
指摘通り対応しましたー

2018-01-12 22:33 UTC, tkhr-sait commented on src/bin/lib/common_utils
> +  env | grep stfw_webhooks_urls_ | cut -d= -f2 |
指摘通り対応しましたー

2018-01-12 22:34 UTC, tkhr-sait commented on src/template/stfw.yml
> +      - http://127.0.0.1:8000/1lazctj1
指摘通り対応しましたー
送信先は
https://webhook.site/#/7e769801-aac8-4335-91df-1ff1c8cfd972

2018-01-12 22:37 UTC, tkhr-sait commented
plugin対応は時間かかりそうなので、一旦指摘対応のみコミット

2018-01-12 23:25 UTC, suwa-sh commented on src/bin/lib/common_utils
> +  export STFW_SERVER_VERSION=$(digdag version 2> /dev/null | grep Server | cut -d' ' -f3)
対応ありがとうございますー
一旦これで大丈夫かと(^-^)b

拡張しづらいので、別issueで
・アプリケーション・アーキテクチャ
・シーケンス x 値引き継ぎ
あたりを整理しますね！

2018-01-12 23:27 UTC, suwa-sh approved these changes

2018-01-12 23:28 UTC, suwa-sh commented
plugin対応は別作業扱いってことで、ここまででmergeしておきますね！

2018-01-12 23:29 UTC, merged